FROM rust:slim-bookworm as builder
WORKDIR /wd

RUN apt update \
    && apt install -yy \
        cmake pkg-config gcc g++ \
        libsasl2-dev libsasl2-dev libssl-dev

COPY . /wd
RUN cargo build --bins --release



FROM debian:bookworm-slim

ENTRYPOINT ["/usr/bin/send2kafka"]

RUN apt update \
    && apt install -yy libsasl2-2

COPY --from=builder /wd/target/release/send2kafka /usr/bin/send2kafka
